### ISSUE TITLE
Behavior doesn't apply when Table is used in a transactional() query.

### ISSUE THREAD

**Issue by ah8r** [lorenzo/audit-stash#11]
It appears that the AuditStash behavior isn't being called when the Table is used as part of a transactional query.

For instance:

``` php
$schedules_table->connection()->transactional(function() use ($schedules_table, $schedules) {
    foreach ($schedules as $schedule)
    {
        $schedules_table->save($schedule, ['atomic' => false]);
    }
}
```

**Comment by lorenzo** [comment]
No, it does not. It is one of many missing features. You can force it to do it manually, though. Let me know if you need help getting that to work

**Comment by ah8r** [comment]
Yes, please if you could let me know how to do it manually that would be really helpful.

**Comment by aceat64** [comment]
I'm also running into this issue, being able to at least force it manually would be good.

**Comment by lorenzo** [comment]
@aceat64 If I tell you how to do it would you volunteer for documenting it?

**Comment by aceat64** [comment]
Sure

**Comment by lorenzo** [comment]
@aceat64 This is what I personally do:

``` php
<?php
namespace App\Model\Audit;
use Cake\Utility\Text;
use SplObjectStorage;
class AuditTrail
{
    protected $_auditQueue;
    protected $_auditTransaction;
    public function __construct()
    {
        $this->_auditQueue = new SplObjectStorage;
        $this->_auditTransaction = Text::uuid();
    }
    public function toSaveOptions()
    {
        return [
            '_auditQueue' => $this->_auditQueue,
            '_auditTransaction' => $this->_auditTransaction
        ];
    }
}
```

``` php
$trail = new AuditTrail();
$success = $connection->transactional(function () use ($trail) {

    $table1->save($data1, $trail->toSaveOptions());
    $table2->save($data2, $trail->toSaveOptions());
    ....
    $tableN->save($dataN, $trail->toSaveOptions());

    return true;
});

if ($success) {
    $event = new Event('Model.afterCommit', $table);
    $table->behaviors()->get('AuditLog')->afterCommit($event, $result, $auditTrail->toSaveOptions());
}
```

**Comment by aceat64** [comment]
@lorenzo I'm running into some issues and could use a bit more info. Where is $result coming from? Do I need to run the event for each table?

**Comment by lorenzo** [comment]
You run the event in only one table, typically, if you are saving associations, you call it on the parent.

`$result` needs to be an entity, as that is the signature for the `afterCommit` event. It does not really matter what entity, but I pass the parent entity when saving associations.

**Comment by kevinquinnyo** [comment]
@lorenzo How hard would it be to make transactional saves work natively with this plugin, without the additional hacks above?

My concern is that we as developers can forget to add the code above in certain situations and we will be missing the audit logs.

Do you already have some ideas on how this could be achieved out-of-the-box?  If so, I don't mind taking a stab at it, but I would probably need some guidance.

I know you're busy, so thanks for taking the time if you can.

**Comment by lorenzo** [comment]
The only way I can think of is by having some sort of global state somewhere tracking whether or not a transaction has started in the connection, and then the behaviour would inject the global shared audit state to the `save()` method

Developers would still need to wrap their calls in `transactional()` though
