### ISSUE TITLE
Error when trying to add mapping

### ISSUE THREAD

**Issue by LDSign** [lorenzo/audit-stash#14]
Hi

I cannot use the shell to add the mapping to Elasticsearch:

"Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in D:\Xampp\htdocs\ebsst_v4\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php on line 34"

The command Ive used:

"bin\cake elastic_mapping Employees --use-templates"

Can you help please?

Thanks,
Frank

**Comment by lorenzo** [comment]
Can you figure out what version of elastic it is using?

**Comment by lorenzo** [comment]
Elastica

**Comment by LDSign** [comment]
Yes, of course ;)

https://github.com/ruflin/Elastica/releases/tag/2.3.1

Installed via composer dependency.

**Comment by LDSign** [comment]
Hi

Ive just switched to my own persister.

Could you have a quick look if its a good practice to split the meta data into individual fields and jsonify the original and changed data?

```
namespace App\Persister;

use AuditStash\PersisterInterface;
use Cake\ORM\Entity;
use Cake\ORM\TableRegistry;

class DatabasePersister implements PersisterInterface
{
    public function logEvents(array $auditLogs)
    {
        //pr($auditLogs);
        //die();
        foreach ($auditLogs as $log) {
            $eventType = $log->getEventType();
            $data = [
                'timestamp' => $log->getTimestamp(),
                'transaction' => $log->getTransactionId(),
                'type' => $log->getEventType(),
                'primary_key' => $log->getId(),
                'source' => $log->getSourceName(),
                'parent_source' => $log->getParentSourceName(),
                'original' => ($eventType === 'create' || $eventType === 'delete') ? null : json_encode($log->getOriginal()),
                'changed' => $eventType === 'delete' ? null : json_encode($log->getChanged()),
                'ip' => $log->getMetaInfo()['ip'],
                'url' => $log->getMetaInfo()['url'],
                'user_id' => $log->getMetaInfo()['user'],
            ];

            TableRegistry::get('Audits')->save(new Entity($data));
        }
    }
}
```

And Ive had no luck to populate get the orignal data at the delete event. I think it makes sense to log the original data here. Any idea how to get this in the method above?

Thanks,
Frank

**Comment by lorenzo** [comment]
@LDSign The error seems to come from the library, not the plugin.. which is odd. It is not a bad idea to do what you are doing. I originally stored the fields in Mysql, but became very slow, consumed a lot of space and could not search freely on the fields. If you only want to store, then that is entirely fine

**Comment by angelxmoreno** [comment]
I had the same errors but using the built-in elastic search Persister. I was using ElasticSearch 5.5. I downgraded to 2.4.6 and it works. Looks like the issue is an incompatibility at the ruflin/Elastica level. Thank you for the plugin @lorenzo

**Comment by danfournier** [comment]
@LDSign `$log->getMetaInfo()` returns null in my case. Any idea why? The rest works fine per your example.
