### ISSUE TITLE
Setting priority of this behavior

### ISSUE THREAD

**Issue by danfournier** [lorenzo/audit-stash#18]
I need to set the priority of this plugin's afterSave callback in order to have it fire after another plugin's similar callback. Any ideas?

**Comment by lorenzo** [comment]
Register it as the last behaviour in your table?

**Comment by danfournier** [comment]
Much simpler than what the CakePHP documentation was saying about setting EventListener priorities :)

I registered it lower in the chain and now it doesn't fire at all (no entries in my table, using custom persister that points to MySQL).

I know that the other plugin I'm using also has an afterSave method. I suspect that this is the cause of the audit plugin not firing?

**Comment by lorenzo** [comment]
It will not fire if any afterSave returns false or stops the event with `stopPropagation()` I use this plugin with many other plugins agin `afterSave` and it works fine
