### ISSUE TITLE
Are there any docs for this plugin anywhere?

### ISSUE THREAD

**Issue by dawoodjee** [lorenzo/audit-stash#2]
Is there least a simple guide showing how to best use the plugin anywhere?

**Comment by lorenzo** [comment]
Not yet, I haven't got the time for it.

@adam-je I am willing to guide you through the process of installing and using this plugin in exchange for help with the docs :)

**Comment by ifunk** [comment]
Even just a few paragraphs in the README about what problem it solves and its basic approach would be useful!

**Comment by bravo-kernel** [comment]
This plugin is on my todo list for for this weekend so I am willing to make a start with the docs. That is... if @lorenzo will spoonfeed me through the process :wink:

**Comment by dawoodjee** [comment]
Hi guys, 

Glad you also have the interest. I have absolutely no problem to contribute docs with some guidance. I'm just super tied down right now, probably til weekend after next. So @bravo-kernel please do us the favour. And please make the docs simple for the CakePHP newbies too, I'll contribute with improvements if needed. 

Best of luck!

**Comment by lorenzo** [comment]
@bravo-kernel Thanks! Please ask me any question you need :)

**Comment by bravo-kernel** [comment]
@adam-je it seems I misunderstood the requirements and will not be able to jump in any time soon so... if you are willing to make a start it would be much appreciated

**Comment by aceat64** [comment]
I'm willing to write some basic documentation for this project. Here's what I think I have so far:
1. Use composer to install `lorenzo/audit-stash` and `cakephp/elastic-search`
2. Deploy Elasticsearch (or use AWS Elasticsearch Service)
3. Add datasource configuration
4. Use `elastic_mapping` shell to create mappings in elastic search
5. Using `friendsofcake/crud` to display logs (install `friendsofcake/crud` using composer first)

Right now I'm stuck on trying to figure out what the configuration should look like. If you could get me a basic example, I think I can work out the rest pretty quickly.

**Comment by lorenzo** [comment]
This is the configuration for elastic search. In app.php, the `Datasources` section:

``` php
'auditlog_elastic' => [
            'className' => 'Cake\ElasticSearch\Datasource\Connection',
            'driver' => 'Cake\ElasticSearch\Datasource\Connection',
            'host' => '127.0.0.1',
            'port' => 9200,
            'index' => 'audit-logs',
        ],
```

You can also have indices per day suing this configuration:

``` php
'auditlog_elastic' => [
            'className' => 'Cake\ElasticSearch\Datasource\Connection',
            'driver' => 'Cake\ElasticSearch\Datasource\Connection',
            'host' => '127.0.0.1',
            'port' => 9200,
            'index' => 'audit-logs%s', // Added a %s
        ],
```

**Comment by lorenzo** [comment]
I wrote something in the readme, i hope it helps
