### ISSUE TITLE
Title change not stored in log

### ISSUE THREAD

**Issue by monsurhoq** [lorenzo/audit-stash#23]
I found that **title** field on my table not logged in Audit Log. After that I changed my behavior declarations like below:

        $this->addBehavior('AuditStash.AuditLog', [
            'whitelist' => ['title']
        ]);

But still now not stored title change. I am using my own database persister strategies

**Comment by lorenzo** [comment]
Do other fields get stored?

**Comment by monsurhoq** [comment]
Yes, others fields stored. But not all fields.

**Comment by lorenzo** [comment]
What’s special about your title field? Did it change at all?

**Comment by monsurhoq** [comment]
There is nothing special. Just a simple varchar field. Not only title field, some others field also not changed.

**Comment by lorenzo** [comment]
No idea, then. Try to find a small reproducible example we can add to the tests
