### ISSUE TITLE
Why not only suggest friendsofcake/process-mq as dependency?

### ISSUE THREAD

**Issue by CauanCabral** [lorenzo/audit-stash#24]
Are [this](https://github.com/lorenzo/audit-stash/blob/master/composer.json#L14) really required?

If I want to use only ElasticSearch as storage, there some reason to download/include `process-mq`?

**Comment by lorenzo** [comment]
It is in `require-dev` so I can run the tests. You don't need that, of course. The packages in `require-dev` will not be installed for you
