### ISSUE TITLE
deprecation warning for ServerRequest::here()

### ISSUE THREAD

**Issue by mzumbadoate** [lorenzo/audit-stash#30]
https://github.com/lorenzo/audit-stash/blob/79216666674714bf4eac68bad278dfd2c0bdcb9a/src/Meta/RequestMetadata.php#L64

Deprecated (16384): ServerRequest::here() will be removed in 4.0.0. You should use getRequestTarget() instead. - /var/www/html/vendor/lorenzo/audit-stash/src/Meta/RequestMetadata.php, line: 64

**Comment by lorenzo** [comment]
can you submit a pull request fixing this?

**Comment by mzumbadoate** [comment]
sure, I'll do that
does it require version/build update too?
or just the change itself?

**Comment by lorenzo** [comment]
just the change
