### ISSUE TITLE
Throws an SQL incorrect syntax error on test

### ISSUE THREAD

**Issue by saviobosco** [lorenzo/audit-stash#37]
I tried testing my application with audit log fixture, it blows up showing the error below. I made some research and its seems to be coming from the SQL syntax. 
cakephp version : 3.5.3
```
Unable to insert fixture "App\Test\Fixture\AuditLogsFixture" in "StudentsManager\Test\TestCase\Controller\StudentsControllerTest" test case: 
SQLSTATE[HY000]: General error: 1 near "transaction": syntax error in [/var/www/schoolsystem-online/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 347]
```

**Comment by saviobosco** [comment]
I'm using sqlite as my test database and just found out that transaction is a reserved word in sqlite which I believe is the cause of the problem.

**Comment by lorenzo** [comment]
that makes sense, I'm ok if you want to send a pull request changing the name of that column
