### ISSUE TITLE
CakePHP 4 compatibility

### ISSUE THREAD

**Issue by swiffer** [lorenzo/audit-stash#40]
Hi, ist an updated Version for CakePHP 4 planned / required?

**Comment by swiffer** [comment]
#42 is a starting point

**Comment by gildonei** [comment]
Same here. Any idea when will be possible use with cake4?

**Comment by swiffer** [comment]
@gildonei  - I'm using it within a project with these changes - #43 - however I'm using the tablepersister instead of elastic search.

**Comment by gildonei** [comment]
@swiffer Tnks. Will try.

**Comment by swiffer** [comment]
@gildonei - 3.0.0 is released
