### ISSUE TITLE
psr-4 autoloading standard warning in composer 1.10

### ISSUE THREAD

**Issue by swiffer** [lorenzo/audit-stash#45]
Deprecation Notice: Class AuditStash\Model\Index\AuditLogsIndex located in ./vendor/lorenzo/audit-stash/src\Model\Index\AuditLogsType.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by swiffer** [comment]
superseded by #47 - lgtm @lorenzo

**Comment by lorenzo** [comment]
Thanks!
