### ISSUE TITLE
CakePHP 5 Support

### ISSUE THREAD

**Issue by mixable** [lorenzo/audit-stash#67]
Currently, this plugin requires `"cakephp/orm": "^4.0"`, but the latest version of CakePHP 5 requires `"cakephp/orm": "^5.0". Are there any plans to support CakePHP 5?

Thank you!

**Comment by cnizzardini** [comment]
There is this: https://github.com/lorenzo/audit-stash/pull/64 but idk how its proceeding.

**Comment by dereuromark** [comment]
ping @lorenzo 

If there is no further activity I am able to port this to a different namespace and move on.

**Comment by cnizzardini** [comment]
@dereuromark Does anyone in the community know him on a more personal level? I know he has been involved for sometime...

**Comment by lorenzo** [comment]
this was done
